/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum WorkType {
  Send = 'Send',
  Receive = 'Receive',
  Epoch1 = 'Epoch1',
  Dev = 'Dev'
}
export declare function generateWork(hashHex: string, workType: WorkType): Promise<string>
export declare function validateWork(hashHex: string, workHex: string, workType: WorkType): boolean
